### ISSUE TITLE
Code license?

### ISSUE THREAD

**Issue by dzungpv** [HRVBand/hrv-lib#8]
Hello,
Can you guy add the license type of this library?

**Comment by Fenox** [comment]
yes, we can add a licence

**Comment by dzungpv** [comment]
> 
> 
> yes, we can add a licence

I am working on a project relate to HRV and found your code, it is for commercial, you can use Apache license like some lib you use in this project, or a "copy left" license. If you add other license type, I will find other solution or code my own. And I ask more about Android app, it is a useful app but why it not on Play Store now?

**Comment by Fenox** [comment]
We will probably add the same licence as in the hrv-band app (Apache). The app was in the app store but is not anymore, because it was to much of an effort to maintain it and to comply with the then new data protection laws, for the few downloads we had.

**Comment by dzungpv** [comment]
> 
> 
> We will probably add the same licence as in the hrv-band app (Apache). The app was in the app store but is not anymore, because it was to much of an effort to maintain it and to comply with the then new data protection laws, for the few downloads we had.

Thank you for the clear answer.

**Comment by Fenox** [comment]
Added licence
